import "~/styles/globals.css";

export const metadata = {
  title: "Closet",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex items-center justify-between w-full p-4 text-xl font-bold gap-4">
      <div>CLOSET</div>
      <div>SIGN IN</div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      <body>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
