import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import {ClerkProvider} from "@clerk/nextjs";
import { TopNav } from "../_components/TopNav";

export const metadata = {
  title: "Closet",
  description: "Generated by Aditya Pallipati",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <TopNav />
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
